<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>StrockWay</RootNamespace>
    <AssemblyName>StrockWay</AssemblyName>
    <!-- Permite rodar também em máquinas que só têm .NET 9 ou 10 instalado -->
    <RollForward>LatestMajor</RollForward>
    <!-- Gera o XML com os comentários /// para aparecerem no Swagger -->
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.10" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

</Project>
